### ISSUE TITLE
[3.12] Can't build ninja 1.11.1 from source

### ISSUE THREAD

**Issue by cdce8p** [scikit-build/ninja-python-distributions#220]
Trying to install `ninja` from source with Python 3.12 results in an error.
AFAICT it's because of `versioneer` which was removed some time ago.

- #170

Maybe all that's missing here is a new release?

```
$ pip install --no-binary ninja ninja==1.11.1
Collecting ninja==1.11.1
  Using cached ninja-1.11.1.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        ...
        File "/tmp/pip-install-3smybk6x/ninja_debf47e70b994022aef1019cb1d0f823/versioneer.py", line 344, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by cdce8p** [comment]
@mayeut @henryiii Sorry for pinging you guys directly but this is currently blocking us from building numpy from source on armv7. Would be awesome if it could be addressed, especially since it only needs a new release to work.

**Comment by henryiii** [comment]
Okay, can try to get a release out.

**Comment by henryiii** [comment]
Should work now?

**Comment by cdce8p** [comment]
> Should work now?

Yes, it does 🚀 Thanks @henryiii!
