### ISSUE TITLE
Unable to pip install 1.10.2.1 on Mac

### ISSUE THREAD

**Issue by foundry-markf** [scikit-build/ninja-python-distributions#81]
Hi,

I'm unable to pip install 1.10.2.1 onto my Mac (and several others).

The error I've seen is:
```
(env382) FWMBP064:src mark.final$ pip install ninja==1.10.2.1
Collecting ninja==1.10.2.1
  Using cached https://files.pythonhosted.org/packages/07/2b/84175ca3e5978f9e1be3672b7618c6be713b69e3a50c98617b7ba4422d58/ninja-1.10.2.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ninja
  Building wheel for ninja (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mark.final/dev/conan/env382/bin/python3 /Users/mark.final/dev/conan/env382/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/90/7pnh_dhd19n9lpynqd0ppwt80000gn/T/tmp4x8ea5_h
       cwd: /private/var/folders/90/7pnh_dhd19n9lpynqd0ppwt80000gn/T/pip-install-n2vn6py8/ninja
  Complete output (13 lines):
  Traceback (most recent call last):
    File "/Users/mark.final/dev/conan/env382/bin/cmake", line 6, in <module>
      from cmake import cmake
  ModuleNotFoundError: No module named 'cmake'
    File "/private/var/folders/90/7pnh_dhd19n9lpynqd0ppwt80000gn/T/pip-build-env-ljc4cp78/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/private/var/folders/90/7pnh_dhd19n9lpynqd0ppwt80000gn/T/pip-build-env-ljc4cp78/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 95, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/private/var/folders/90/7pnh_dhd19n9lpynqd0ppwt80000gn/T/pip-build-env-ljc4cp78/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
      raise SKBuildError(
  Traceback (most recent call last):

  Problem with the CMake installation, aborting build. CMake executable is cmake
  ----------------------------------------
  ERROR: Failed building wheel for ninja
  Running setup.py clean for ninja
Failed to build ninja
ERROR: Could not build wheels for ninja which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I also have CMake in my virtual environment:

```
(env382) FWMBP064:src mark.final$ cmake --version
cmake version 3.21.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(env382) FWMBP064:src mark.final$ which cmake
/Users/mark.final/dev/conan/env382/bin/cmake
```

and this is 
```
(env382) FWMBP064:src mark.final$ python --version
Python 3.8.2
```

and my system info
```
(env382) FWMBP064:src mark.final$ uname -a
Darwin FWMBP064.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64
```

I can `pip install ninja==1.10.2` without error.

**Comment by foundry-markf** [comment]
Just as I posted, I thought I should upgrade pip to see if that makes a difference.

```
(env382) FWMBP064:src mark.final$ pip install -U pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/ca/31/b88ef447d595963c01060998cb329251648acf4a067721b0452c45527eb8/pip-21.2.4-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-21.2.4
(env382) FWMBP064:src mark.final$ pip install -U ninja
Requirement already satisfied: ninja in /Users/mark.final/dev/conan/env382/lib/python3.8/site-packages (1.10.2)
Collecting ninja
  Using cached ninja-1.10.2.1-py2.py3-none-macosx_10_9_universal2.macosx_11_0_arm64.macosx_11_0_universal2.whl (225 kB)
Installing collected packages: ninja
  Attempting uninstall: ninja
    Found existing installation: ninja 1.10.2
    Uninstalling ninja-1.10.2:
      Successfully uninstalled ninja-1.10.2
Successfully installed ninja-1.10.2.1
```

and it does.

Sorry for the noise!

**Comment by mayeut** [comment]
Thanks for the report @foundry-markf.
That's not noise, it even has all information to see that 1.10.2.1 is missing the `macosx_10_9_x86_64` platform tag on the macOS wheel. We'll need to fix this.
